dist: ubuntu-precise
language: cpp
matrix:
  include:
    addons: 
      apt: 
        packages: 
          - clang-3.9
          - libclang-3.9-dev
          - libllvm3.9
          - libstdc++-6-dev
    env: COMPILER=clang++3.9
    compiler: clang
install: if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
script: make CXX=$COMPILER