
dist: ubuntu-precise
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - libclang-3.9-dev
      - libllvm3.9
      - libstdc++-6-dev
before_script:
  - travis_wait 10 ./extra-tools/CITPreBuildDep.sh
script: make