dist: trusty
sudo: required
language: cpp
env:
  global:
   - secure: "lW9TiQPsS9IXFxwPlrw56nTRGS3s+Ev6X0F1cQTPyrOSL5ST9pyyoCmV5cfiagQX9mKxAaBPUAhIohtrP22V0Ug/Nxfln6S/1I4Qbm579un0vch6Y3d3grFVkRAS/KYdHpq26RJ6z1u8HuEksrJDkGK6UZm/0hDs5ynH3ky2uYjI7RpclEr3Acmt8JVQKuGgt6XnPSgApEZAJY92PlregFzDhNaChPydXYdPtseEfEE4KTe3VRVIvCnhFiX4o/tRsInhpYLNnY7CxG9DZ+oBL1ypECdzVAlPpbpCcN/r3HjnQ7tqNxkqx6ODll4KgtckiE92TULJUU4zba6vGQgQTe22zxA6PAbqA6Za0fojkRlgFPHIGRuuH7G06tkVoMPwhky6ZXxAtQ/nJUkFrhECdXJyBk2p9Q17IRnGluUkb7fTx6kfE3A6uASm2mNbK0fggHMokeOSwa3aoZfXZ7lsslM9MPuXICkXvizrHCfJIlKnG+l7pSd0dCgBEgc9mfSbtCo6xZGIoJcWePLgwNNnX3Nzzk1QDKvYURgYGS25p0Zp1cptOQncXg4yyXaeyN88dcP9rme4woS7fAZAF9mRJ371ijxr+U+BCh+M3JuOSjWCCSfjjawHpHxq0QoLRrIKY8KZRRHxKgPEWGccWjvoIvtoVXBCVA6eNU2JCEMuWh4="
matrix:
  include:
    os: linux
    compiler: clang
    addons:
      coverity_scan:
        project:
          name: "bloodstalker/mutator"
          description: "Build submitted via Travis CI"
        notification_email: thabogre@gmail.com
        build_command_prepend: "./configure; make clean"
        build_command:   "make CXX=clang-3.9 LLVM_CONF=llvm-config-3.9 BUILD_MODE=COV_NO_CLANG"
        branch_pattern: Master

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script: 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - travis_wait 30 sudo apt-get install clang-3.9 libclang-3.9-dev libclang-common-3.9-dev libllvm3.9 llvm-3.9-dev llvm-3.9 -y
  #- sudo apt-get install clang-4.0 libclang-common-4.0-dev libclang-4.0-dev libclang1-4.0 libclang1-4.0-dbg libllvm4.0 libllvm4.0-dbg lldb-4.0 llvm-4.0 llvm-4.0-dev llvm-4.0-runtime lldb-4.0-dev liblldb-4.0-dbg
script: make CXX=clang-3.9 LLVM_CONF=llvm-config-3.9 BUILD_MODE=COV_NO_CLANG