dist: ubuntu-precise
language: cpp
matrix:
  include:
    os: linux
    compiler: clang
    addons: 
      apt: 
        packages: 
          - clang-3.7
          - libclang-3.7-dev
          - libllvm3.7
          - libstdc++-6-dev
    env: COMPILER=clang++-3.7
script: make CXX=$COMPILER