#dist: ubuntu-precise
#language: cpp
#matrix:
#  include:
#    os: linux
#    compiler: clang
#    addons: 
#      apt: 
#        packages: 
#          - clang-3.9
#          - libclang-3.9-dev
#          - libllvm3.9
#          - libstdc++-6-dev
#    env: COMPILER=clang++-3.9

#script: make CXX=$COMPILER
sudo: required

language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
          packages: ['clang-3.9']
      env: 
        - COMPILER=clang++-3.9
        - LLVMCONFIG=llvm-config-3.9

# Activate when 3.7 is released and the repository is available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
#          packages: ['clang-3.7']
#      env: COMPILER=clang++-3.7

# Activate when we are allowed to use MacOS X
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang++
before_install:
  - sudo apt-get update -qq

script:
  make CXX=$COMPILER LLVM_CONF=$LLVMCONFIG