dist: ubuntu-precise
language: cpp
compiler: clang
matrix:
  include:
    addons: 
      apt: 
        packages: 
          - clang-3.9
          - libclang-3.9-dev
          - libllvm3.9
          - libstdc++-6-dev
    env: COMPILER=clang++3.7      
script: make CXX=$COMPILER