
dist: ubuntu-precise
sudo: required
before_install: sudo apt-get remove clang
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - libclang-3.9-dev
      - libllvm3.9
      - libstdc++-6-dev
      - clang-3.9
script: make