
dist: ubuntu-precise
language: cpp
matrix:
  include:  
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.9
      env: COMPILER=clang++3.9  
addons:
  apt:
    packages:
      - libclang-3.9-dev
      - libllvm3.9
      - libstdc++-6-dev
script: make